[build.environment]
    CI="FALSE"
    NODE_OPTIONS = "--max_old_space_size=4096"
    REACT_APP__ENV="PRODUCTION"
    # App Configurations ISPRODLIVE only for alca/mig/stake apps
    REACT_APP__ISPRODLIVE="TRUE"
    REACT_APP__ALCA_LIVE="TRUE"
    # Ethereum Configuration
    REACT_APP__ETHEREUM_ENDPOINT_LOCAL="http://localhost:8545"
    REACT_APP__ETHEREUM_ENDPOINT_STAGING="https://hh.staging.alice.net"
    REACT_APP__ETHEREUM_ENDPOINT_PRODUCTION="https://eth.alice.net"
    # Contract Configuration
    REACT_APP__STORAGE_CONTRACT_ADDRESS="0x0"
    REACT_APP_FACTORY_CONTRACT_ADDRESS="0x3B89020198932655cf459F5d3821bB9637965D59"
    REACT_APP_ALCA_CONTRACT_ADDRESS="0x0"
    REACT_APP_ALCB_CONTRACT_ADDRESS="0x0"
    REACT_APP_LOCKUP_CONTRACT_ADDRESS="0x0"
    REACT_APP_MADTOKEN_CONTRACT_ADDRESS="0x0"
    REACT_APP_PUBLICSTAKING_CONTRACT_ADDRESS="0x0"
    REACT_APP_STAKINGROUTERV1_CONTRACT_ADDRESS="0x0"
    REACT_APP_VALIDATORSTAKING_CONTRACT_ADDRESS="0x0"
