[build.environment]
    CI="FALSE"
    NODE_OPTIONS = "--max_old_space_size=4096"
    # Ethereum Configuration
    REACT_APP__ETHEREUM_ENDPOINT_LOCAL="http://localhost:8545"
    REACT_APP__ETHEREUM_ENDPOINT_STAGING="https://hh.staging.alice.net"
    REACT_APP__ETHEREUM_ENDPOINT_PRODUCTION="https://eth.alice.net"
    # Contract Configuration - Universal Across All Apps
    REACT_APP__FACTORY_CONTRACT_ADDRESS="0x4b6dF6B299fB6414f45719E0d9e1889269a7843E"
    REACT_APP__ALCA_CONTRACT_ADDRESS="0x0"
    REACT_APP__ALCB_CONTRACT_ADDRESS="0x0"
    REACT_APP__LOCKUP_CONTRACT_ADDRESS="0x0"
    REACT_APP__MADTOKEN_CONTRACT_ADDRESS="0x0"
    REACT_APP__PUBLICSTAKING_CONTRACT_ADDRESS="0x0"
    REACT_APP__STAKINGROUTERV1_CONTRACT_ADDRESS="0x0"
    REACT_APP__VALIDATORSTAKING_CONTRACT_ADDRESS="0x0"
    # ALCA APP CONFIG - Specific to ALCA Application ( Migrate, Stake, Lockup )
    REACT_APP__ALCA_ENVIRONMENT="STAGING"
    REACT_APP__ALCA_LIVE="FALSE"
    # ALCA SIMPLE_STAKE - Specific to ALCA Simple Stake App
    REACT_APP__SIMPLE_STAKE_ENVIRONMENT="STAGING"
