name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@1f8873e97e3c8f58161a323b7c568c1f623a1c4d
        with:
          project: Alpha
          column: In Progress
          repo-token: ${{ secrets.ISSUE_ADDER_PAT }}
