name: Move assigned pull requests into To do

on:
  issues:
    types: [opened, reopened, assigned, unassigned, closed]
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run hello
      - run: echo Hello!
      
      - name: "Call pm task"
        uses: ACatThatPrograms/pm-actions@main
        with:
          project_name: Alpha
          new_column_name: Backlog
          assign_column_name: In Progress
          review_column_name: In Review
          closed_column_name: Done
          repo-token: ${{ secrets.ISSUE_ADDER_PAT }}
