name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.2
        with:
          project: Alpha Team Board
          column: In Progress
          repo-token: ${{ secrets.ISSUE_ADDER_PAT }}
