name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.ISSUE_ADDER_PAT }}
jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign new issues to project-board
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/alicenet/projects/5'
