name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.ISSUE_ADDER_PAT }}

jobs:
  assign_to_alpha:
    runs-on: ubuntu-latest
    name: Push issue to Alpha Project Board
    steps:
    - name: Assign new issues to Alpha Team Project Board
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/alicenet/projects/7'
        column_name: "Backlog"
